### ISSUE TITLE
fluctuation of values and zero position

### ISSUE THREAD

**Issue by pipes80-collab** [FreeJoy-Team/FreeJoyConfiguratorQt#5]
I upload this video to explain it better, as you can see from the video the oscillation of the raw and output values are normal? increasing the filter they tend to oscillate less ... another thing is the position of the output value that after calibration never stays still but tends to increase a little, is this also normal?
another problem the system crash with green screen of death when setting the poolling of the usb port to 1 ms and freejoy device connected to a usb type c port
[USBXHCI.zip](https://github.com/FreeJoy-Team/FreeJoyConfiguratorQt/files/5934520/USBXHCI.zip)
[FreeJoy Configurator v1.6.2 (1.1.2) 2021-02-05 19-15-42.mp4.zip](https://github.com/FreeJoy-Team/FreeJoyConfiguratorQt/files/5934523/FreeJoy.Configurator.v1.6.2.1.1.2.2021-02-05.19-15-42.mp4.zip)

**Comment by Reksotiv** [comment]
1)Yes, raw and output values are normal. This may be caused by your hardware design. Try to keep your wires as short as possible, use shielding on long wires and place analog signal wires far from digital signal wires and other noise sources. Built-in filtering and deadzone should help (also try dynamic deadzone, it detects axis movement and fix output value when axis is held).
2)Reduce the maximum calibration to the maximum raw value and the output will be minimum
3)Have you tried updating USB and chipset drivers?

**Comment by pipes80-collab** [comment]
1. Yes I think to do this because I like more short the wired.
2. I calibrate with automatic calibration in freejoy configuration Qt maybe it's more good change manually that value max?
3. No driver update for z490 chipset...I like to leave always updated my driver

**Comment by Reksotiv** [comment]
Yes, slightly correct the maximum value.
What usb cable are you using, usb micro to usb type-c? I do not have a type-c, but in USB 3.1 it works without problems. FreJoy is a USB 2.0 device, there is no benefit to using the fastest port.

**Comment by pipes80-collab** [comment]
I have used an adaptador for plug usb a to usb type c on the pc

**Comment by Reksotiv** [comment]
it is noise. I already answered https://github.com/FreeJoy-Team/FreeJoyConfiguratorQt/issues/5
